use codux_runtime::{
    i18n::translate, runtime_paths::app_display_name, settings::locale_from_language_setting,
};
use gpui::{Menu, MenuItem, NoAction, OsAction, SystemMenuType, actions};

actions!(
    codux_menu,
    [
        ShowAbout,
        OpenSettings,
        CheckUpdates,
        ExportDiagnostics,
        OpenRuntimeLog,
        OpenLiveLog,
        OpenWebsite,
        OpenGithub,
        HideCodux,
        HideOthers,
        ShowAll,
        NewProject,
        OpenProjectFolder,
        CloseCurrentProject,
        CloseActive,
        CloseWindow,
        QuitCodux,
        ViewTerminal,
        ViewFiles,
        ViewReview,
        ViewStats,
        ToggleProjects,
        ToggleTasks,
        OpenGitPanel,
        OpenFilesPanel,
        OpenAiPanel,
        OpenSshPanel,
        CreateSplit,
        CreateVerticalSplit,
        CloseSplit,
        CreateTask,
        EditorSave,
        EditorSearch,
        MinimizeWindow,
        ZoomWindow,
        ToggleFullscreen,
    ]
);

struct MenuLabels {
    app_name: String,
    about: String,
    settings: String,
    check_updates: String,
    services: String,
    hide_app: String,
    hide_others: String,
    show_all: String,
    quit: String,
    file: String,
    edit: String,
    workspace: String,
    view: String,
    window: String,
    help: String,
    new_project: String,
    open_folder: String,
    close_current_project: String,
    close_active: String,
    close_window: String,
    undo: String,
    redo: String,
    cut: String,
    copy: String,
    paste: String,
    select_all: String,
    terminal: String,
    files: String,
    review: String,
    stats: String,
    projects_sidebar: String,
    tasks_sidebar: String,
    git_panel: String,
    files_panel: String,
    ai_panel: String,
    ssh_panel: String,
    create_split: String,
    create_split_vertical: String,
    close_split: String,
    create_task: String,
    editor_save: String,
    editor_search: String,
    toggle_fullscreen: String,
    minimize: String,
    zoom: String,
    diagnostics: String,
    runtime_log: String,
    live_log: String,
    website: String,
    github: String,
}

impl MenuLabels {
    fn load(language: &str) -> Self {
        let locale = locale_from_language_setting(language);
        let tr = |key: &str, fallback: &str| translate(&locale, key, fallback);
        let app_name = app_display_name();
        Self {
            app_name: app_name.to_string(),
            about: tr("menu.app.about_format", "About %@").replace("%@", app_name),
            settings: tr("menu.app.settings", "Settings..."),
            check_updates: tr("menu.app.check_updates", "Check for Updates..."),
            services: tr("menu.app.services", "Services"),
            hide_app: tr("menu.app.hide_format", "Hide %@").replace("%@", app_name),
            hide_others: tr("menu.app.hide_others", "Hide Others"),
            show_all: tr("menu.app.show_all", "Show All"),
            quit: tr("menu.app.quit_format", "Quit %@").replace("%@", app_name),
            file: tr("menu.file", "File"),
            edit: tr("menu.edit", "Edit"),
            workspace: tr("menu.workspace", "Workspace"),
            view: tr("menu.view", "View"),
            window: tr("menu.window", "Window"),
            help: tr("menu.help", "Help"),
            new_project: tr("menu.file.new_project", "New Project"),
            open_folder: tr("menu.file.open_folder", "Open Folder..."),
            close_current_project: tr("menu.file.close_current_project", "Close Current Project"),
            close_active: tr("menu.file.close_current_split", "Close Current Split"),
            close_window: tr("menu.file.close_window", "Close Window"),
            undo: tr("common.undo", "Undo"),
            redo: tr("common.redo", "Redo"),
            cut: tr("common.cut", "Cut"),
            copy: tr("common.copy", "Copy"),
            paste: tr("common.paste", "Paste"),
            select_all: tr("common.select_all", "Select All"),
            terminal: tr("workspace.create_split.terminal", "Terminal"),
            files: tr("titlebar.files", "Files"),
            review: tr("titlebar.review", "Review"),
            stats: tr("stats.title", "AI Usage Dashboard"),
            projects_sidebar: tr("menu.view.projects_sidebar", "Projects Sidebar"),
            tasks_sidebar: tr("menu.view.tasks_sidebar", "Worktree Sidebar"),
            git_panel: tr("menu.view.open_git_panel", "Open Git Panel"),
            files_panel: tr("menu.view.open_files_panel", "Open Files Panel"),
            ai_panel: tr("menu.view.open_ai_panel", "Open AI Panel"),
            ssh_panel: tr("menu.view.open_ssh_panel", "Open SSH Panel"),
            create_split: tr("menu.view.create_split", "Split Right"),
            create_split_vertical: tr("menu.view.create_split_vertical", "Split Down"),
            close_split: tr("menu.view.close_split", "Close Split"),
            create_task: tr("shortcut.task.create", "New Worktree"),
            editor_save: tr("common.save", "Save"),
            editor_search: tr("shortcut.editor.search", "Search File"),
            toggle_fullscreen: tr("menu.view.toggle_full_screen", "Toggle Full Screen"),
            minimize: tr("menu.window.minimize", "Minimize"),
            zoom: tr("menu.window.zoom", "Zoom"),
            diagnostics: tr("menu.help.export_diagnostics", "Export Diagnostics..."),
            runtime_log: tr("menu.help.open_runtime_log", "Open Runtime Log"),
            live_log: tr("menu.help.open_live_log", "Open Live Log"),
            website: tr("menu.help.website", "Official Website"),
            github: tr("menu.help.github", "GitHub"),
        }
    }
}

pub(crate) fn codux_menus(language: &str) -> Vec<Menu> {
    let labels = MenuLabels::load(language);
    vec![
        Menu {
            name: labels.app_name.into(),
            disabled: false,
            items: vec![
                MenuItem::action(labels.about.clone(), ShowAbout),
                MenuItem::action(labels.check_updates.clone(), CheckUpdates),
                MenuItem::separator(),
                MenuItem::action(labels.settings, OpenSettings),
                MenuItem::separator(),
                MenuItem::os_submenu(labels.services, SystemMenuType::Services),
                MenuItem::separator(),
                MenuItem::action(labels.hide_app, HideCodux),
                MenuItem::action(labels.hide_others, HideOthers),
                MenuItem::action(labels.show_all, ShowAll),
                MenuItem::separator(),
                MenuItem::action(labels.quit, QuitCodux),
            ],
        },
        Menu {
            name: labels.file.into(),
            disabled: false,
            items: vec![
                MenuItem::action(labels.new_project, NewProject),
                MenuItem::action(labels.open_folder, OpenProjectFolder),
                MenuItem::separator(),
                MenuItem::action(labels.close_current_project, CloseCurrentProject),
                MenuItem::separator(),
                MenuItem::action(labels.close_active, CloseActive),
                MenuItem::action(labels.close_window.clone(), CloseWindow),
            ],
        },
        Menu {
            name: labels.edit.into(),
            disabled: false,
            items: vec![
                MenuItem::os_action(labels.undo, NoAction, OsAction::Undo),
                MenuItem::os_action(labels.redo, NoAction, OsAction::Redo),
                MenuItem::separator(),
                MenuItem::os_action(labels.cut, NoAction, OsAction::Cut),
                MenuItem::os_action(labels.copy, NoAction, OsAction::Copy),
                MenuItem::os_action(labels.paste, NoAction, OsAction::Paste),
                MenuItem::os_action(labels.select_all, NoAction, OsAction::SelectAll),
            ],
        },
        Menu {
            name: labels.workspace.into(),
            disabled: false,
            items: vec![
                MenuItem::action(labels.terminal, ViewTerminal),
                MenuItem::action(labels.files, ViewFiles),
                MenuItem::action(labels.review, ViewReview),
                MenuItem::action(labels.stats, ViewStats),
                MenuItem::separator(),
                MenuItem::action(labels.projects_sidebar, ToggleProjects),
                MenuItem::action(labels.tasks_sidebar, ToggleTasks),
                MenuItem::separator(),
                MenuItem::action(labels.create_split, CreateSplit),
                MenuItem::action(labels.create_split_vertical, CreateVerticalSplit),
                MenuItem::action(labels.close_split, CloseSplit),
                MenuItem::action(labels.create_task, CreateTask),
                MenuItem::separator(),
                MenuItem::action(labels.editor_save, EditorSave),
                MenuItem::action(labels.editor_search, EditorSearch),
            ],
        },
        Menu {
            name: labels.view.into(),
            disabled: false,
            items: vec![
                MenuItem::action(labels.git_panel, OpenGitPanel),
                MenuItem::action(labels.files_panel, OpenFilesPanel),
                MenuItem::action(labels.ai_panel, OpenAiPanel),
                MenuItem::action(labels.ssh_panel, OpenSshPanel),
                MenuItem::separator(),
                MenuItem::action(labels.toggle_fullscreen, ToggleFullscreen),
            ],
        },
        Menu {
            name: labels.window.into(),
            disabled: false,
            items: vec![
                MenuItem::action(labels.minimize, MinimizeWindow),
                MenuItem::action(labels.zoom, ZoomWindow),
                MenuItem::separator(),
                MenuItem::action(labels.close_window, CloseWindow),
            ],
        },
        Menu {
            name: labels.help.into(),
            disabled: false,
            items: vec![
                MenuItem::action(labels.about, ShowAbout),
                MenuItem::action(labels.check_updates, CheckUpdates),
                MenuItem::separator(),
                MenuItem::action(labels.diagnostics, ExportDiagnostics),
                MenuItem::action(labels.runtime_log, OpenRuntimeLog),
                MenuItem::action(labels.live_log, OpenLiveLog),
                MenuItem::separator(),
                MenuItem::action(labels.website, OpenWebsite),
                MenuItem::action(labels.github, OpenGithub),
            ],
        },
    ]
}
